import React, { useState } from "react";
import { Sparkles, Upload, Wand2, Image as ImageIcon, Tag, FileText, Megaphone, Check } from "lucide-react";
import MerchantLayout from "../components/merchant/MerchantLayout";
import api from "../lib/api";
import { toast } from "sonner";

const RAW_DEMO = "https://static.prod-images.emergentagent.com/jobs/7eafffce-c685-4839-ad08-06796579c4de/images/ec5665f39e798be41fe86083e99a5d4c91342b61fdb3c0fed0ac8470b9f5ae30.png";
const AFTER_DEMO = "https://static.prod-images.emergentagent.com/jobs/7eafffce-c685-4839-ad08-06796579c4de/images/85d2c0f8f4172341be04027aee7a0cdd867b695317ee9a9a01a9e2b11653670e.png";

export default function AIStudio() {
  const [rawPreview, setRawPreview] = useState(RAW_DEMO);
  const [enhanced, setEnhanced] = useState(null);
  const [enhancing, setEnhancing] = useState(false);
  const [productName, setProductName] = useState("Hand-Block Indigo Kurta");
  const [category, setCategory] = useState("Ethnic Wear");
  const [notes, setNotes] = useState("Pure cotton, hand-block printed in Bagru, Jaipur. Festive ready.");
  const [copy, setCopy] = useState(null);
  const [genCopy, setGenCopy] = useState(false);
  const [file, setFile] = useState(null);

  const onFile = (f) => {
    if (!f) return;
    setFile(f);
    setRawPreview(URL.createObjectURL(f));
    setEnhanced(null);
  };

  const enhanceImage = async () => {
    setEnhancing(true);
    setEnhanced(null);
    try {
      if (!file) {
        // Demo mode: simulate the wow with the curated after image
        await new Promise((r) => setTimeout(r, 1800));
        setEnhanced(AFTER_DEMO);
        toast.success("AI catalog shot ready");
      } else {
        const fd = new FormData();
        fd.append("file", file);
        const { data } = await api.post("/merchant/ai/enhance-image", fd, {
          headers: { "Content-Type": "multipart/form-data" },
        });
        if (data.enhanced_base64) {
          setEnhanced(`data:image/png;base64,${data.enhanced_base64}`);
        } else {
          setEnhanced(data.fallback_url || AFTER_DEMO);
        }
        toast.success("AI transformation complete");
      }
    } catch (e) {
      toast.error("Enhancement failed — showing demo result");
      setEnhanced(AFTER_DEMO);
    } finally { setEnhancing(false); }
  };

  const generateCopy = async () => {
    setGenCopy(true);
    setCopy(null);
    try {
      const { data } = await api.post("/merchant/ai/copy", {
        product_name: productName, category, notes,
      });
      setCopy(data);
      toast.success("Copy generated by Claude 4.5");
    } catch (e) {
      toast.error("Copy generation failed");
    } finally { setGenCopy(false); }
  };

  return (
    <MerchantLayout>
      <div className="p-8 md:p-12 max-w-6xl">
        <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-[#E68910]/10 text-[#E68910] text-xs font-semibold mb-3">
          <Sparkles size={12} /> AI CATALOG ENGINE
        </div>
        <h1 data-testid="ai-studio-title" className="display text-4xl md:text-5xl font-bold text-[#1A2B4C]">Turn raw photos into editorial catalogs.</h1>
        <p className="text-[#595959] mt-2 max-w-2xl">Upload a phone shot, our AI does the rest — studio backdrops, lifestyle imagery, descriptions, hashtags and campaign copy.</p>

        {/* IMAGE WORKFLOW */}
        <section className="mt-10 bg-white border border-[#E5E2DC] rounded-3xl p-6 md:p-8">
          <h2 className="display text-2xl font-bold text-[#1A2B4C] flex items-center gap-2"><ImageIcon size={20} /> Step 1 · Catalog image</h2>
          <div className="mt-6 grid md:grid-cols-2 gap-6">
            <div>
              <div className="text-[11px] uppercase tracking-widest text-[#595959] mb-2 font-semibold">Raw photo</div>
              <div className="relative aspect-[4/5] rounded-2xl overflow-hidden bg-[#FDFBF7] border-2 border-dashed border-[#E5E2DC]">
                <img src={rawPreview} alt="raw" className="w-full h-full object-cover" />
              </div>
              <label data-testid="upload-zone" className="mt-3 flex items-center justify-center gap-2 px-5 py-3 rounded-full border-2 border-dashed border-[#E5E2DC] cursor-pointer hover:border-[#1A2B4C] transition">
                <Upload size={16} /> <span className="text-sm font-medium">Upload your photo</span>
                <input type="file" accept="image/*" onChange={(e) => onFile(e.target.files?.[0])} className="hidden" />
              </label>
            </div>
            <div>
              <div className="text-[11px] uppercase tracking-widest text-[#E68910] mb-2 font-semibold">AI Studio result</div>
              <div className="relative aspect-[4/5] rounded-2xl overflow-hidden bg-[#1A2B4C] border-2 border-[#E68910]">
                {enhancing && (
                  <div className="absolute inset-0 flex flex-col items-center justify-center text-white z-10 bg-[#1A2B4C]/95">
                    <Sparkles size={28} className="text-[#E68910] animate-spin mb-3" />
                    <div className="text-sm">Gemini Nano Banana<br />composing studio shot…</div>
                  </div>
                )}
                {enhanced ? (
                  <img src={enhanced} alt="enhanced" className="w-full h-full object-cover bf-fadeup" />
                ) : (!enhancing && (
                  <div className="absolute inset-0 flex items-center justify-center text-white/40 text-sm">Click "Transform with AI" to see the magic</div>
                ))}
                {enhanced && !enhancing && (
                  <div className="absolute top-3 left-3 px-2 py-1 rounded-full bg-white/95 text-[#1A2B4C] text-[10px] font-bold flex items-center gap-1">
                    <Check size={11} /> AI ENHANCED
                  </div>
                )}
              </div>
              <button onClick={enhanceImage} disabled={enhancing} data-testid="enhance-btn" className="mt-3 w-full flex items-center justify-center gap-2 px-5 py-3 rounded-full bg-[#1A2B4C] text-white font-semibold hover:bg-[#101D36] disabled:opacity-60 transition">
                <Wand2 size={16} /> {enhancing ? "Enhancing…" : "Transform with AI"}
              </button>
            </div>
          </div>
        </section>

        {/* COPY WORKFLOW */}
        <section className="mt-8 bg-white border border-[#E5E2DC] rounded-3xl p-6 md:p-8">
          <h2 className="display text-2xl font-bold text-[#1A2B4C] flex items-center gap-2"><FileText size={20} /> Step 2 · Product copy</h2>
          <div className="mt-6 grid md:grid-cols-5 gap-6">
            <div className="md:col-span-2 space-y-3">
              <input data-testid="copy-product-name" value={productName} onChange={(e) => setProductName(e.target.value)} placeholder="Product name" className="w-full px-4 py-3 rounded-xl border border-[#E5E2DC] outline-none focus:border-[#1A2B4C]" />
              <input data-testid="copy-category" value={category} onChange={(e) => setCategory(e.target.value)} placeholder="Category" className="w-full px-4 py-3 rounded-xl border border-[#E5E2DC] outline-none focus:border-[#1A2B4C]" />
              <textarea data-testid="copy-notes" value={notes} onChange={(e) => setNotes(e.target.value)} rows={5} placeholder="Your notes — fabric, fit, occasion, story…" className="w-full px-4 py-3 rounded-xl border border-[#E5E2DC] outline-none focus:border-[#1A2B4C]" />
              <button onClick={generateCopy} disabled={genCopy} data-testid="generate-copy-btn" className="w-full inline-flex items-center justify-center gap-2 px-5 py-3 rounded-full bg-[#E68910] text-white font-semibold hover:bg-[#C9770E] disabled:opacity-60">
                <Sparkles size={16} /> {genCopy ? "Crafting…" : "Generate with Claude 4.5"}
              </button>
            </div>
            <div data-testid="copy-output" className="md:col-span-3 bg-[#FDFBF7] rounded-2xl p-5 min-h-72 border border-[#E5E2DC]">
              {!copy && !genCopy && (
                <div className="text-[#595959] text-sm italic">Your AI-generated title, description, hashtags, SEO meta and campaign hook will appear here.</div>
              )}
              {genCopy && <div className="text-[#1A2B4C] flex items-center gap-2"><Sparkles size={16} className="animate-spin text-[#E68910]" /> Composing premium copy…</div>}
              {copy && (
                <div className="space-y-4 bf-fadeup">
                  <div>
                    <div className="text-[10px] uppercase tracking-widest text-[#E68910] font-semibold mb-1">Title</div>
                    <h3 className="display text-xl font-bold text-[#1A2B4C]">{copy.title}</h3>
                  </div>
                  <div>
                    <div className="text-[10px] uppercase tracking-widest text-[#E68910] font-semibold mb-1">Description</div>
                    <p className="text-sm text-[#1C1C1C] leading-relaxed">{copy.description}</p>
                  </div>
                  {copy.highlights?.length > 0 && (
                    <div>
                      <div className="text-[10px] uppercase tracking-widest text-[#E68910] font-semibold mb-1">Highlights</div>
                      <ul className="text-sm text-[#1C1C1C] space-y-1">
                        {copy.highlights.map((h, i) => <li key={i} className="flex gap-2"><Check size={14} className="text-[#4F7363] mt-0.5 shrink-0" />{h}</li>)}
                      </ul>
                    </div>
                  )}
                  {copy.tags?.length > 0 && (
                    <div>
                      <div className="text-[10px] uppercase tracking-widest text-[#E68910] font-semibold mb-1 flex items-center gap-1"><Tag size={11} /> Hashtags</div>
                      <div className="flex flex-wrap gap-1.5">
                        {copy.tags.map((t, i) => <span key={i} className="px-2.5 py-1 rounded-full bg-white border border-[#E5E2DC] text-xs">#{String(t).replace(/^#/, "")}</span>)}
                      </div>
                    </div>
                  )}
                  {copy.campaign_copy && (
                    <div>
                      <div className="text-[10px] uppercase tracking-widest text-[#E68910] font-semibold mb-1 flex items-center gap-1"><Megaphone size={11} /> Campaign hook</div>
                      <p className="text-sm italic text-[#1A2B4C]">"{copy.campaign_copy}"</p>
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        </section>
      </div>
    </MerchantLayout>
  );
}
